/**
 * Unit tests for the All-In Cost Engine.
 *
 * Golden values here are hand-computed and shown in the comments (spec §8).
 * They are NOT captured from the implementation — a fixture generated by the
 * code under test can only prove the code agrees with itself.
 */
import { describe, it, expect } from 'vitest';
import { computeCost, baseMonthlyCents, ancillaryMonthlyCents, oneTimeCents } from './cost';
import type { CareScenario } from '../schemas';

function scenario(overrides: Partial<CareScenario> = {}): CareScenario {
  return {
    id: 's1',
    label: 'Assisted living',
    careType: 'assisted_living',
    stateCode: 'TX',
    ancillary: [],
    ...overrides,
  };
}

describe('Given a residential scenario priced from the national median', () => {
  it('When no extras are added, Then the all-in cost equals the advertised base', () => {
    const result = computeCost(scenario());
    // Assisted living national median: $6,200/mo = 620000 cents.
    expect(result.advertisedBaseCents).toBe(620_000);
    expect(result.allInMonthlyCents).toBe(620_000);
    expect(result.deltaPercent).toBe(0);
  });

  it('When no state figure exists, Then it falls back to the national median and says so', () => {
    const result = computeCost(scenario({ stateCode: 'TX' }));
    expect(result.isNationalFallback).toBe(true);
  });
});

describe('Given a facility with a care tier, add-ons and a community fee', () => {
  const withFees = scenario({
    fees: {
      communityFeeCents: 400_000, // $4,000 one-time
      careLevelTierCents: 150_000, // $1,500/mo
      annualEscalatorRate: 0.04,
      addOns: [
        { id: 'a1', label: 'Medication management', kind: 'medication_management', monthlyCents: 50_000 },
        { id: 'a2', label: 'Incontinence supplies', kind: 'incontinence_supplies', monthlyCents: 40_000 },
      ],
    },
  });

  it('When the cost is computed, Then all-in is base + tier + add-ons', () => {
    // 620000 + 150000 + 50000 + 40000 = 860000 ($8,600/mo)
    expect(computeCost(withFees).allInMonthlyCents).toBe(860_000);
  });

  it('When compared to the brochure rate, Then the delta is 38.7% above advertised', () => {
    // (860000 - 620000) / 620000 * 100 = 38.709677...%
    expect(computeCost(withFees).deltaPercent).toBeCloseTo(38.7097, 3);
  });

  it('When month one is priced, Then the community fee is included exactly once', () => {
    const result = computeCost(withFees);
    // 860000 + 400000 = 1260000 ($12,600 in month one)
    expect(result.oneTimeCents).toBe(400_000);
    expect(result.firstMonthCents).toBe(1_260_000);
  });
});

describe('Given hourly in-home care', () => {
  it('When priced at 40 hrs/week, Then the monthly cost uses 52 weeks over 12 months', () => {
    const result = baseMonthlyCents(
      scenario({ careType: 'in_home_health_aide', hoursPerWeek: 40 }),
    );
    // $35/hr * 40 * 52 / 12 = 3500 * 2080 / 12 = 7280000 / 12 = 606666.67 -> 606667
    expect(result.cents).toBe(606_667);
  });

  it('When priced at the survey 44 hrs/week, Then it matches the published annual figure', () => {
    const result = baseMonthlyCents(
      scenario({ careType: 'in_home_health_aide', hoursPerWeek: 44 }),
    );
    // $35 * 44 * 52 = $80,080/yr published. /12 = $6,673.33/mo = 667333 cents.
    expect(result.cents).toBe(667_333);
  });

  it('When no hours are set, Then the cost is zero rather than a silent default', () => {
    expect(baseMonthlyCents(scenario({ careType: 'in_home_health_aide' })).cents).toBe(0);
  });
});

describe('Given a real quote from a real facility', () => {
  it('When an override is set, Then it replaces the median entirely', () => {
    const result = computeCost(scenario({ costOverrideCents: 725_000 }));
    expect(result.advertisedBaseCents).toBe(725_000);
    expect(result.usedOverride).toBe(true);
    expect(result.isNationalFallback).toBe(false);
  });
});

describe('Given ancillary expenses at mixed cadences', () => {
  const withAncillary = scenario({
    ancillary: [
      { id: 'e1', label: 'Medications', category: 'medication', amountCents: 12_000, cadence: 'monthly', taxDeductibleCandidate: true },
      { id: 'e2', label: 'Dental', category: 'dental_vision_hearing', amountCents: 120_000, cadence: 'annual', taxDeductibleCandidate: true },
      { id: 'e3', label: 'Grab bars', category: 'home_modification', amountCents: 90_000, cadence: 'one_time', taxDeductibleCandidate: false },
    ],
  });

  it('When normalised, Then annual spend is divided by twelve and one-time is excluded', () => {
    // 12000 + (120000 / 12 = 10000) = 22000/mo
    expect(ancillaryMonthlyCents(withAncillary)).toBe(22_000);
  });

  it('When one-time costs are totalled, Then they land in month one only', () => {
    expect(oneTimeCents(withAncillary)).toBe(90_000);
  });
});

describe('Given unpaid family care', () => {
  it('When priced, Then there are no fees because the cost is opportunity cost', () => {
    expect(computeCost(scenario({ careType: 'family_provided' })).allInMonthlyCents).toBe(0);
  });
});

describe('Given a scenario with all three one-time cost kinds (community fee + ancillary one-time + buy-in entry)', () => {
  // §6 lesson "Format a Total and Its Parts at the Same Precision":
  // the parts in CostBreakdown must be able to be presented alongside the
  // aggregate without arithmetic errors rounding the parts or the total.
  // Regression protection for the refactor in computeCost — if anyone
  // re-inlines the one-time sum or changes the buy-in fold, this test
  // breaks immediately.
  const buyInContract = {
    entryCents: 750_000, // $7,500 IL buy-in
    amortized: false,
    refundSchedule: [],
    monthlyServiceCentsRate: 0,
  };
  const fullyLoaded = scenario({
    careType: 'independent_living',
    costOverrideCents: 0,
    fees: {
      communityFeeCents: 400_000, // $4,000 community fee
      buyInContract,
      annualEscalatorRate: 0.04,
      addOns: [],
      careLevelTierCents: 0,
    },
    ancillary: [
      {
        id: 'e1',
        label: 'Grab bars',
        category: 'home_modification',
        amountCents: 90_000, // $900
        cadence: 'one_time',
        taxDeductibleCandidate: false,
      },
    ],
  });

  it('Then oneTimeCents === communityFeeCents + ancillaryOneTime + buyInEntryCents', () => {
    // Hand-computed: 400_000 (community) + 90_000 (ancillary one-time)
    //                + 750_000 (buy-in entry) = 1_240_000 cents.
    const result = computeCost(fullyLoaded);
    expect(result.oneTimeCents).toBe(1_240_000);
    expect(result.buyInEntryCents).toBe(750_000);
    expect(result.oneTimeCents).toBe(
      400_000 + 90_000 + result.buyInEntryCents,
    );
  });

  it('Then firstMonthCents is consistent with the same oneTimeCents aggregate', () => {
    // firstMonthCents == allIn + oneTimeCents == 0 + 1_240_000 = 1_240_000.
    // (override = 0 ⇒ allIn = 0; one-time aggregate unchanged.)
    // Regression: if firstMonthCents ever stop reading oneTimeCents(),
    // these two will diverge.
    const result = computeCost(fullyLoaded);
    expect(result.firstMonthCents).toBe(result.allInMonthlyCents + result.oneTimeCents);
    expect(result.firstMonthCents).toBe(1_240_000);
  });
});
