#!/usr/bin/env node
// Emit Tasks — the deterministic "propose" step of the agentic loop.
//
// Reads harness-status.json (produced by harness-status.mjs) and turns each
// open finding into a self-contained work order under tasks/. A work order is
// a bring-your-own-agent prompt: it names the context, the spec reference, the
// exact acceptance gate that must go green, and the definition of done — so any
// AI agent (Claude Code, Cursor, Copilot, Aider, ...) can claim it and act,
// with no provider baked into the harness.
//
// Idempotent: an existing tasks/<id>.md is never clobbered (an agent may be
// mid-work on it). Resolved findings leave a stale file behind, which
// emit-tasks flags so it can be pruned.
//
// Usage:
//   node scripts/emit-tasks.mjs           # sense first, then emit
//   node scripts/emit-tasks.mjs --no-sense # reuse existing harness-status.json
//   node scripts/emit-tasks.mjs --prune    # delete task files with no live finding

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const statusPath = join(repoRoot, 'harness-status.json');
const tasksDir = join(repoRoot, 'tasks');

const args = new Set(process.argv.slice(2));
const noSense = args.has('--no-sense');
const prune = args.has('--prune');

// Refresh the senses unless told to reuse the existing snapshot.
if (!noSense) {
  execFileSync(process.execPath, [join(__dirname, 'harness-status.mjs'), '--quiet'], { stdio: 'inherit' });
}

if (!existsSync(statusPath)) {
  console.error('harness-status.json not found. Run: node scripts/harness-status.mjs');
  process.exit(1);
}

const status = JSON.parse(readFileSync(statusPath, 'utf8'));
if (!existsSync(tasksDir)) mkdirSync(tasksDir, { recursive: true });

function evidenceBlock(f) {
  if (!f.evidence?.length) return '';
  const rows = f.evidence.map((e) => `- \`${e.file}:${e.line}\` — \`${e.snippet}\``).join('\n');
  return `\n## Evidence\n\n${rows}\n`;
}

function workOrder(f) {
  const spec = f.specRef ? `\n- **Spec:** [\`${f.specRef}\`](../${f.specRef})` : '';
  return `# Work Order: ${f.title}

> **Auto-generated by the harness.** This is a bring-your-own-agent task — any
> AI coding agent may claim it. Follow \`.agents/AGENTS.md\` while you work.
> Do **not** edit this header; delete the file once the acceptance gate is green.

- **Finding ID:** \`${f.id}\`
- **App:** \`${f.app}\`
- **Type:** ${f.type}
- **Severity:** ${f.severity}
- **Acceptance gate:** \`${f.gate}\`${spec}

## Context

${f.detail}
${evidenceBlock(f)}
## Definition of done

1. Read \`.agents/AGENTS.md\` and, if present, the app's spec before changing code.
2. Make the change in \`projects/${f.app}\` (or the spec, if the spec is wrong — flag that in the PR).
3. The acceptance gate above must pass:
   - \`guardrails\` / missing spec → \`node scripts/harness-status.mjs --gate\` exits 0 (this
     finding is **blocking**; the offending pattern must be gone from the cited files).
   - \`validate-specs*\` → \`node scripts/harness-status.mjs --strict\` no longer reports \`${f.id}\`.
   - \`manual-review\` → resolve or explicitly defer each item, updating the spec checkbox accordingly.
4. Re-run \`node scripts/emit-tasks.mjs --prune\` to retire this work order.
5. Open a PR — never self-merge; a human reviews.

_If fixing this taught you a reusable rule, add it to \`.agents/AGENTS.md\` and,
if it is mechanically detectable, add a guardrail to \`scripts/harness-status.mjs\`
so the harness catches it automatically next time._
`;
}

const liveIds = new Set(status.findings.map((f) => f.id));
let created = 0, skipped = 0;
for (const f of status.findings) {
  const file = join(tasksDir, `${f.id}.md`);
  if (existsSync(file)) { skipped++; continue; }
  writeFileSync(file, workOrder(f));
  created++;
  console.log(`  + tasks/${f.id}.md`);
}

// Detect (and optionally prune) task files whose finding is resolved.
const existing = readdirSync(tasksDir).filter((n) => n.endsWith('.md') && n !== 'README.md');
const stale = existing.filter((n) => !liveIds.has(n.replace(/\.md$/, '')));
let pruned = 0;
for (const n of stale) {
  if (prune) { rmSync(join(tasksDir, n)); pruned++; console.log(`  - tasks/${n} (resolved, pruned)`); }
}

console.log(`\nWork orders: ${created} created, ${skipped} already open, ${status.findings.length} live finding(s).`);
if (stale.length && !prune) {
  console.log(`${stale.length} task file(s) have no live finding (resolved): ${stale.join(', ')}`);
  console.log(`Run 'node scripts/emit-tasks.mjs --prune' to retire them.`);
} else if (prune && pruned) {
  console.log(`Pruned ${pruned} resolved work order(s).`);
}
