#!/usr/bin/env node
// Self-test for fix-repowise-mcp-paths.mjs (see that file's header for why
// it exists: repowise re-injects an absolute repo path into .mcp.json /
// .vscode/mcp.json on every re-index, and there's no flag to suppress it).
//
// Zero dependencies; run with:
//   node scripts/fix-repowise-mcp-paths.test.mjs

import { stripAbsolutePathArgs, fixMcpConfig } from './fix-repowise-mcp-paths.mjs';

let failures = 0;
const ok = (cond, label) => {
  if (cond) console.log(`✓ ${label}`);
  else {
    console.error(`✗ ${label}`);
    failures += 1;
  }
};

/* ---- stripAbsolutePathArgs ------------------------------------------------- */

{
  // Given a repowise entry regenerated by `repowise init`, with the absolute
  // repo path re-injected between "mcp" and "--transport"
  const entry = { command: 'repowise', args: ['mcp', '/home/user/agentic-app-harness', '--transport', 'stdio'] };
  // When stripAbsolutePathArgs runs
  const { args, changed } = stripAbsolutePathArgs(entry);
  // Then the absolute path is removed and the rest of the args survive, in order
  ok(changed === true, 'stripAbsolutePathArgs reports a change when an absolute path is present');
  ok(
    JSON.stringify(args) === JSON.stringify(['mcp', '--transport', 'stdio']),
    'stripAbsolutePathArgs removes only the absolute-path element, preserving order',
  );
}

{
  // Given an already-clean repowise entry (this script already ran, or the
  // committed file was never regenerated)
  const entry = { command: 'repowise', args: ['mcp', '--transport', 'stdio'] };
  // When stripAbsolutePathArgs runs
  const { args, changed } = stripAbsolutePathArgs(entry);
  // Then nothing changes — idempotent
  ok(changed === false, 'stripAbsolutePathArgs is a no-op on an already-clean entry');
  ok(JSON.stringify(args) === JSON.stringify(['mcp', '--transport', 'stdio']), 'stripAbsolutePathArgs leaves clean args untouched');
}

{
  // Given a *different* MCP server that legitimately takes an absolute-path
  // argument (command is not "repowise")
  const entry = { command: 'some-other-server', args: ['--root', '/home/user/agentic-app-harness'] };
  // When stripAbsolutePathArgs runs
  const { args, changed } = stripAbsolutePathArgs(entry);
  // Then it is left alone — the fix is scoped to repowise's own entry only
  ok(changed === false, 'stripAbsolutePathArgs does not touch a non-repowise server entry');
  ok(JSON.stringify(args) === JSON.stringify(['--root', '/home/user/agentic-app-harness']), 'stripAbsolutePathArgs leaves a non-repowise entry\'s args exactly as-is');
}

/* ---- fixMcpConfig ----------------------------------------------------------- */

{
  // Given a parsed .mcp.json shape with a dirty repowise entry among others
  const json = {
    mcpServers: {
      repowise: { command: 'repowise', args: ['mcp', '/some/absolute/path', '--transport', 'stdio'] },
      other: { command: 'other-tool', args: ['--flag'] },
    },
  };
  // When fixMcpConfig runs over the mcpServers key
  const { json: fixed, changed } = fixMcpConfig(json, 'mcpServers');
  // Then only the repowise entry is rewritten, and the input object is untouched
  ok(changed === true, 'fixMcpConfig reports a change when any entry needed fixing');
  ok(
    JSON.stringify(fixed.mcpServers.repowise.args) === JSON.stringify(['mcp', '--transport', 'stdio']),
    'fixMcpConfig fixes the repowise entry',
  );
  ok(
    JSON.stringify(fixed.mcpServers.other.args) === JSON.stringify(['--flag']),
    'fixMcpConfig leaves sibling entries alone',
  );
  ok(
    json.mcpServers.repowise.args.length === 4,
    'fixMcpConfig does not mutate the input object (still 4 args on the original)',
  );
}

{
  // Given a .vscode/mcp.json shape (servers key, not mcpServers) that is
  // already clean
  const json = { servers: { repowise: { command: 'repowise', args: ['mcp', '--transport', 'stdio'] } } };
  // When fixMcpConfig runs over the servers key
  const { changed } = fixMcpConfig(json, 'servers');
  // Then nothing is reported as changed
  ok(changed === false, 'fixMcpConfig is a no-op end-to-end on an already-clean file shape');
}

/* ---- summary ---------------------------------------------------------------- */

if (failures > 0) {
  console.error(`\n${failures} check(s) failed.`);
  process.exit(1);
} else {
  console.log('\nAll checks passed.');
}
